---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install required system packages
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - jq
      - docker-ce

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Add needed groups to docker container
  group:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - actions

- name: Add the user 'actions'
  user:
    name: actions
    comment: Github Actions User
    group: docker
    shell: /bin/bash
    home: "{{ RUNNER_BASEDIR }}"

- command: chdir=/tmp {{ item }}
  with_items:
  - curl -O -L {{ RUNNER_BASEURL }}/v{{ RUNNER_VERSION }}/{{ RUNNER_PACKAGE }}
  - tar zxvf {{ RUNNER_PACKAGE }} -C {{ RUNNER_BASEDIR }} 
  - chown -R actions:actions {{ RUNNER_BASEDIR }}

- command: chdir=/opt/actions-runner {{ item }}
  with_items:
  - sudo ./bin/installdependencies.sh
